/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      
      ScientificCalculator calc = new ScientificCalculator();

        double result= calc.cubeOf(4.0);

        System.out.println("cube =" + result);
        
        //int result = ScientificCalculator.modulo(5, 2);

        //System.out.println("modulo =" + result);

       // double result = calc.squareOf(3);

      //System.out.println("square =" + result);

       //double result = calc.powerOf(1,2);
       // System.out.println("pow =" + result);
       
      //double result = calc.squareRoot(8);
        //System.out.println("sqrt =" + result);

      
        //double result = calc.modulo_double(6,3);
        //System.out.println("modulo_double " + result);
        

           // System.out.println("Starting QCalc..");
        
       // StandardCalculator calc = new StandardCalculator();
        
          // calc.add(1, 2);
        
          // System.out.println(calc.getresult());
          //  calc.substract(1, 2);
        
           // System.out.println(calc.getresult());
            //calc.multiply(1, 2);
        
           // System.out.println(calc.getresult());
         // calc.divide(1, 2);
        
           // System.out.println(calc.getresult());
    
    
    
        
        
       // System.out.println(new App().getGreeting());
    }
    }


